name: Publish Package to npmjs

on:
  # 手动触发
  workflow_dispatch:
  # 提交触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Branch
        uses: actions/checkout@v4.2.1
        with:
          ref: main
      # Setup .npmrc file to publish to npm
      - name: Install Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.6.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
