name: Publish to npm
on:
  # 手动触发
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.2.1 # 克隆代码

      - name: Install Node.js
        uses: actions/setup-node@v4.0.4 # 安装 Node.js
        with:
          node-version: "20.6.0"

      - name: Build step
        run: 'npm install && npm run build' # 安装依赖并打包

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 调用 github 填写的 NPM_TOKEN
